### ISSUE TITLE
`\dot\vec{q}^2` 的排版问题

### ISSUE THREAD

**Issue by kexplorning** [laserroger/Physics-from-Symmetry#80]
又看了看一些数学公式排版，发现，像

https://github.com/laserroger/Physics-from-Symmetry/blob/be876416feeede6ab734346f3092dc073a53c1f7/TEX%20File/Chaps/Chap4.tex#L322-L324

排版出的数学公式不好看。还有，这种写法，`\dot\vec{q}^2` 可能会有兼容性问题，使用 `\dot{\vec{q}}^2` 会好一点（代码看起来也清楚点）。

对于这个的修正方式，我好像没有找到很好的解决方法……

**Comment by laserroger** [comment]
这个是大家tex风格和习惯的问题，我也不知道怎么解决。。
